package api

// Shared request/response helpers for every /api handler. Owned by the foundation (BE0);
// area owners use them but do not edit this file.

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"log/slog"
	"net/http"
	"strconv"
	"strings"
	"syscall"

	"rainy/internal/artwork"
	"rainy/internal/auth"
	"rainy/internal/model"
	"rainy/internal/scanner"
	"rainy/internal/store"
	"rainy/internal/util"
)

// maxJSONBody bounds request bodies read by decodeJSON.
const maxJSONBody = 1 << 20 // 1 MiB

// Error codes (docs/architecture/contract.md §7).
const (
	CodeBadRequest     = "bad_request"     // 400
	CodeUnauthorized   = "unauthorized"    // 401
	CodeForbidden      = "forbidden"       // 403
	CodeNotFound       = "not_found"       // 404
	CodeConflict       = "conflict"        // 409
	CodeReadonly       = "readonly"        // 409
	CodeRateLimited    = "rate_limited"    // 429
	CodeInternal       = "internal"        // 500
	CodeNotImplemented = "not_implemented" // 501
	CodeUnavailable    = "unavailable"     // 503
)

// Error is an error carrying an HTTP status and API error code. Return one from your
// code (or wrap one) and pass it to writeErr to control the response exactly.
type Error struct {
	Status  int
	Code    string
	Message string
}

func (e *Error) Error() string { return e.Message }

// newError builds an *Error.
func newError(status int, code, format string, args ...any) *Error {
	return &Error{Status: status, Code: code, Message: fmt.Sprintf(format, args...)}
}

// badRequest is a 400 bad_request error.
func badRequest(format string, args ...any) *Error {
	return newError(http.StatusBadRequest, CodeBadRequest, format, args...)
}

// forbidden is a 403 forbidden error.
func forbidden(format string, args ...any) *Error {
	return newError(http.StatusForbidden, CodeForbidden, format, args...)
}

// notFound is a 404 not_found error.
func notFound(format string, args ...any) *Error {
	return newError(http.StatusNotFound, CodeNotFound, format, args...)
}

// writeJSON writes v as JSON with the given status (Cache-Control: no-store).
func writeJSON(w http.ResponseWriter, status int, v any) {
	b, err := json.Marshal(v)
	if err != nil {
		slog.Error("api: encoding response", "err", err)
		writeError(w, http.StatusInternalServerError, CodeInternal, "internal server error")
		return
	}
	h := w.Header()
	h.Set("Content-Type", "application/json; charset=utf-8")
	if h.Get("Cache-Control") == "" {
		h.Set("Cache-Control", "no-store")
	}
	w.WriteHeader(status)
	_, _ = w.Write(b)
}

// writeNoContent answers 204.
func writeNoContent(w http.ResponseWriter) { w.WriteHeader(http.StatusNoContent) }

// writeError writes {"error":{"code":code,"message":msg}} with status.
func writeError(w http.ResponseWriter, status int, code, msg string) {
	h := w.Header()
	h.Set("Content-Type", "application/json; charset=utf-8")
	h.Set("Cache-Control", "no-store")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(map[string]any{"error": map[string]string{"code": code, "message": msg}})
}

// errorFrom maps an error to (status, code, message):
//
//	*Error                                          → as given
//	store.ErrNotFound, artwork.ErrNotFound          → 404 not_found
//	store.ErrConflict, scanner.ErrScanInProgress    → 409 conflict
//	read-only file system / permission denied       → 409 readonly
//	store.ErrInvalid, auth.ErrValidation, util.ErrUnsafePath → 400 bad_request
//	auth.ErrInvalidCredentials                      → 401 unauthorized
//	auth.ErrRateLimited                             → 429 rate_limited
//	errors.ErrUnsupported (stubbed features)        → 501 not_implemented
//	context.Canceled / DeadlineExceeded             → 503 unavailable
//	anything else                                   → 500 internal (message hidden)
func errorFrom(err error) (status int, code, msg string) {
	var ae *Error
	switch {
	case err == nil:
		return http.StatusOK, "", ""
	case errors.As(err, &ae):
		return ae.Status, ae.Code, ae.Message
	case errors.Is(err, store.ErrNotFound), errors.Is(err, artwork.ErrNotFound):
		return http.StatusNotFound, CodeNotFound, "not found"
	case errors.Is(err, store.ErrConflict), errors.Is(err, scanner.ErrScanInProgress):
		return http.StatusConflict, CodeConflict, err.Error()
	case errors.Is(err, syscall.EROFS), errors.Is(err, fs.ErrPermission):
		return http.StatusConflict, CodeReadonly,
			"the music folder is read-only or not writable by the server; mount it read-write to edit files (" + err.Error() + ")"
	case errors.Is(err, store.ErrInvalid), errors.Is(err, auth.ErrValidation), errors.Is(err, util.ErrUnsafePath):
		return http.StatusBadRequest, CodeBadRequest, err.Error()
	case errors.Is(err, auth.ErrInvalidCredentials):
		return http.StatusUnauthorized, CodeUnauthorized, err.Error()
	case errors.Is(err, auth.ErrRateLimited):
		return http.StatusTooManyRequests, CodeRateLimited, err.Error()
	case errors.Is(err, errors.ErrUnsupported):
		return http.StatusNotImplemented, CodeNotImplemented, err.Error()
	case errors.Is(err, context.Canceled), errors.Is(err, context.DeadlineExceeded):
		return http.StatusServiceUnavailable, CodeUnavailable, "request cancelled"
	}
	return http.StatusInternalServerError, CodeInternal, "internal server error"
}

// writeErr writes the response for err (see errorFrom). 5xx errors are logged with the
// request method and path.
func writeErr(w http.ResponseWriter, r *http.Request, err error) {
	status, code, msg := errorFrom(err)
	if status >= 500 && !errors.Is(err, context.Canceled) {
		slog.Error("api error", "method", r.Method, "path", r.URL.Path, "status", status, "err", err)
	}
	writeError(w, status, code, msg)
}

// decodeJSON decodes the request body (at most 1 MiB) into dst. An empty body leaves dst
// untouched and is not an error, so optional bodies work. Malformed JSON yields a 400 *Error.
func decodeJSON(w http.ResponseWriter, r *http.Request, dst any) error {
	r.Body = http.MaxBytesReader(w, r.Body, maxJSONBody)
	dec := json.NewDecoder(r.Body)
	if err := dec.Decode(dst); err != nil {
		var mbe *http.MaxBytesError
		switch {
		case errors.Is(err, io.EOF):
			return nil
		case errors.As(err, &mbe):
			return newError(http.StatusRequestEntityTooLarge, CodeBadRequest, "request body too large (max %d bytes)", maxJSONBody)
		default:
			return badRequest("invalid JSON body: %v", err)
		}
	}
	if dec.More() {
		return badRequest("invalid JSON body: unexpected data after the JSON value")
	}
	return nil
}

// pageParams reads ?offset, ?limit, ?sort and ?order. limit defaults to defaultLimit and is
// clamped to [1, maxLimit]; offset is ≥ 0; order is "asc", "desc" or "".
func pageParams(r *http.Request, defaultLimit, maxLimit int) (offset, limit int, sort, order string) {
	offset = max(queryInt(r, "offset", 0), 0)
	limit = queryInt(r, "limit", defaultLimit)
	if limit <= 0 {
		limit = defaultLimit
	}
	if maxLimit > 0 && limit > maxLimit {
		limit = maxLimit
	}
	q := r.URL.Query()
	sort = strings.TrimSpace(q.Get("sort"))
	switch o := strings.ToLower(strings.TrimSpace(q.Get("order"))); o {
	case "asc", "desc":
		order = o
	}
	return offset, limit, sort, order
}

// queryBool reports whether query parameter name is "1", "true", "yes" or "on".
func queryBool(r *http.Request, name string) bool {
	switch strings.ToLower(strings.TrimSpace(r.URL.Query().Get(name))) {
	case "1", "true", "yes", "on":
		return true
	}
	return false
}

// queryInt returns the integer query parameter name, or def when absent or invalid.
func queryInt(r *http.Request, name string, def int) int {
	v, err := strconv.Atoi(strings.TrimSpace(r.URL.Query().Get(name)))
	if err != nil {
		return def
	}
	return v
}

// queryInt64 returns the int64 query parameter name, or def when absent or invalid.
func queryInt64(r *http.Request, name string, def int64) int64 {
	v, err := strconv.ParseInt(strings.TrimSpace(r.URL.Query().Get(name)), 10, 64)
	if err != nil {
		return def
	}
	return v
}

// queryList returns the values of a comma-separated (and/or repeated) query parameter,
// trimmed, empty entries dropped; nil when absent.
func queryList(r *http.Request, name string) []string {
	var out []string
	for _, v := range r.URL.Query()[name] {
		for _, p := range strings.Split(v, ",") {
			if p = strings.TrimSpace(p); p != "" {
				out = append(out, p)
			}
		}
	}
	return out
}

// userFrom returns the authenticated user (nil on public routes without a session).
func userFrom(r *http.Request) *model.User { return auth.UserFrom(r.Context()) }

// Page is the JSON shape of paginated lists.
type Page[T any] struct {
	Items []T `json:"items"`
	Total int `json:"total"`
}

// writePage writes {"items": items, "total": total} (items is never null).
func writePage[T any](w http.ResponseWriter, items []T, total int) {
	if items == nil {
		items = []T{}
	}
	writeJSON(w, http.StatusOK, Page[T]{Items: items, Total: total})
}

// nonNil returns s, or an empty slice when s is nil (so it marshals as []).
func nonNil[T any](s []T) []T {
	if s == nil {
		return []T{}
	}
	return s
}
