#!/usr/bin/env bash
# Generates a small, fully tagged test library for Rainy into testdata/music (or $1).
#
#   bash scripts/gen-testdata.sh [output-dir]
#
# Requires ffmpeg with libmp3lame, libvorbis, libopus and the native aac/flac encoders.
# Works in Git Bash on Windows and on Linux/macOS. Idempotent: the output directory is
# recreated on every run (it is only deleted if it was created by this script).
#
# Coverage: mp3 (ID3v2.4, UTF-8), flac, m4a (AAC), ogg vorbis, opus, wav; Chinese, Japanese
# and English metadata; a multi-disc album; a compilation; embedded covers (mp3/flac/m4a),
# folder images (cover.jpg, folder.png), an album without art, artist.jpg; synced .lrc
# sidecars and an embedded LYRICS tag; an untagged file; multi-value genres; "3/10" track
# numbers; full dates and bare years; hidden (.hidden) and Synology (@eaDir) folders whose
# audio must be ignored by the scanner.
set -euo pipefail

# Git Bash: never rewrite arguments that look like POSIX paths (we only pass relative paths).
export MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*'
export LC_ALL="${LC_ALL:-C.UTF-8}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/testdata/music}"
MARKER=".rainy-testdata"

die() { echo "gen-testdata: $*" >&2; exit 1; }

command -v ffmpeg >/dev/null 2>&1 || die "ffmpeg is required (https://ffmpeg.org/download.html)"
encoders="$(ffmpeg -hide_banner -encoders 2>/dev/null)"
for enc in libmp3lame libvorbis libopus aac flac pcm_s16le mjpeg png; do
  grep -qE "^ [A-Z.]{6} $enc " <<<"$encoders" || die "ffmpeg lacks the '$enc' encoder"
done

if [[ -e "$OUT" ]]; then
  if [[ -f "$OUT/$MARKER" || -z "$(ls -A "$OUT" 2>/dev/null)" ]]; then
    rm -rf "$OUT"
  else
    die "$OUT exists and was not created by this script; refusing to delete it"
  fi
fi
mkdir -p "$OUT"
cd "$OUT"
echo "generated by scripts/gen-testdata.sh — safe to delete" >"$MARKER"
WORK=".work"
mkdir -p "$WORK"
trap 'rm -rf "$OUT/$WORK"' EXIT

FF=(ffmpeg -hide_banner -loglevel error -nostdin -y)

# ---------------------------------------------------------------- images

# image <out> <size> <color0> <color1>: a diagonal two-colour gradient (solid colour fallback).
image() {
  local out=$1 size=$2 c0=$3 c1=$4
  mkdir -p "$(dirname "$out")"
  if ! "${FF[@]}" -f lavfi -i "gradients=s=${size}x${size}:c0=${c0}:c1=${c1}:x0=0:y0=0:x1=${size}:y1=${size}:d=1" \
      -frames:v 1 -update 1 "$out" 2>/dev/null; then
    "${FF[@]}" -f lavfi -i "color=c=${c0}:s=${size}x${size}:d=1" -frames:v 1 -update 1 "$out"
  fi
}

image "$WORK/summer.jpg" 600 0xF59E0B 0xEF4444     # 夏日微风 (embedded, mp3)
image "$WORK/rain.jpg" 600 0x6366F1 0x0EA5E9       # 雨上がりの空 (embedded, m4a)
image "$WORK/aurora.png" 1200 0x10B981 0x1E3A8A    # Aurora Lights (embedded 1200px PNG, flac)
image "$WORK/hits.jpg" 600 0xEC4899 0x8B5CF6       # Summer Hits (embedded, mp3)

# ---------------------------------------------------------------- audio

# source <duration> <seed> [noise]: lavfi audio source spec.
source() {
  local d=$1 seed=$2 kind=${3:-tone}
  if [[ $kind == noise ]]; then
    local colors=(pink white brown)
    echo "anoisesrc=d=${d}:c=${colors[$((seed % 3))]}:a=0.15:r=44100"
  else
    echo "sine=frequency=$((220 + (seed * 97) % 660)):sample_rate=44100:duration=${d}"
  fi
}

# duration <seed>: 3–12 seconds.
duration() { echo $((3 + ($1 * 7) % 10)); }

TRACKS=0

# track <out> <seed> <cover|-> <tone|noise> [ffmpeg metadata args...]
track() {
  local out=$1 seed=$2 cover=$3 kind=$4
  shift 4
  local ext="${out##*.}"
  local inputs=(-f lavfi -i "$(source "$(duration "$seed")" "$seed" "$kind")")
  local maps=(-map 0:a)
  local codec=()
  case "$ext" in
    mp3)  codec=(-c:a libmp3lame -b:a 96k -id3v2_version 4 -write_id3v1 0) ;;
    flac) codec=(-c:a flac -sample_fmt s16) ;;
    m4a)  codec=(-c:a aac -b:a 96k) ;;
    ogg)  codec=(-c:a libvorbis -q:a 1) ;;
    opus) codec=(-c:a libopus -b:a 48k) ;;
    wav)  codec=(-c:a pcm_s16le -ar 22050 -ac 1) ;;
    *) die "unsupported extension: $ext" ;;
  esac
  if [[ $cover != - ]]; then
    inputs+=(-i "$cover")
    maps+=(-map 1:v -c:v copy -disposition:v:0 attached_pic)
    if [[ $ext == mp3 || $ext == flac ]]; then
      maps+=(-metadata:s:v "title=Album cover" -metadata:s:v "comment=Cover (front)")
    fi
  fi
  mkdir -p "$(dirname "$out")"
  "${FF[@]}" "${inputs[@]}" "${maps[@]}" "${codec[@]}" -map_metadata -1 \
    -fflags +bitexact -flags:a +bitexact "$@" "$out"
  TRACKS=$((TRACKS + 1))
}

# lrc <file> <title> <artist> <line>...: synced sidecar, one line every 1.5 s.
lrc() {
  local file=$1 title=$2 artist=$3
  shift 3
  {
    printf '[ti:%s]\n[ar:%s]\n[by:rainy gen-testdata]\n' "$title" "$artist"
    local i=0 ms
    for line in "$@"; do
      ms=$((i * 1500))
      printf '[%02d:%02d.%02d]%s\n' $((ms / 60000)) $(((ms / 1000) % 60)) $(((ms % 1000) / 10)) "$line"
      i=$((i + 1))
    done
  } >"$file"
}

seed=0
next() { seed=$((seed + 1)); }

# 1) 林雨晴 / 夏日微风 — mp3, ID3v2.4 UTF-8, embedded JPEG cover, "N/6" track numbers, full date.
dir="林雨晴/夏日微风 (2021)"
titles=("夏日微风" "海边的约定" "晴天日记" "蝉鸣" "橘子汽水" "晚安，夏天")
for i in "${!titles[@]}"; do
  n=$((i + 1)); next
  track "$dir/$(printf '%02d' $n) ${titles[$i]}.mp3" $seed "$WORK/summer.jpg" tone \
    -metadata "title=${titles[$i]}" -metadata "artist=林雨晴" -metadata "album_artist=林雨晴" \
    -metadata "album=夏日微风" -metadata "track=$n/${#titles[@]}" -metadata "disc=1/1" \
    -metadata "date=2021-06-18" -metadata "genre=Mandopop" -metadata "composer=林雨晴" \
    -metadata "comment=测试数据 · generated"
done
# Synology thumbnail folder with audio inside: must be ignored.
next
track "$dir/@eaDir/01 夏日微风.mp3" $seed - tone -metadata "title=SHOULD NOT BE SCANNED (@eaDir)"

# 2) 林雨晴 / 城市夜雨 — flac, cover.jpg in the folder, .lrc sidecars, one embedded LYRICS tag,
#    year only, multi-value genre "Pop; Rock".
dir="林雨晴/城市夜雨 (2019)"
image "$dir/cover.jpg" 600 0x334155 0x0F172A
titles=("城市夜雨" "霓虹" "末班车" "伞下" "天亮以前")
for i in "${!titles[@]}"; do
  n=$((i + 1)); next
  extra=()
  if [[ $n == 3 ]]; then
    extra=(-metadata $'LYRICS=[00:00.00]末班车 — 内嵌歌词\n[00:01.50]窗外的灯一盏一盏\n[00:03.00]载着我驶向夜的尽头')
  fi
  track "$dir/$(printf '%02d' $n) ${titles[$i]}.flac" $seed - tone \
    -metadata "TITLE=${titles[$i]}" -metadata "ARTIST=林雨晴" -metadata "ALBUMARTIST=林雨晴" \
    -metadata "ALBUM=城市夜雨" -metadata "TRACKNUMBER=$n/${#titles[@]}" -metadata "DATE=2019" \
    -metadata "GENRE=Pop; Rock" "${extra[@]}"
done
lrc "$dir/01 城市夜雨.lrc" "城市夜雨" "林雨晴" "雨落在城市的屋檐" "灯火映在你的眼" "我们走过长长的街" "直到夜色褪去"
lrc "$dir/02 霓虹.lrc" "霓虹" "林雨晴" "霓虹闪烁" "人潮来去" "只有你在原地"
# artist image next to the artist's album folders.
image "林雨晴/artist.jpg" 600 0xFDA4AF 0xBE185D

# 3) 星野ミライ / 雨上がりの空 — m4a (AAC), Japanese, embedded cover, genre "J-Pop/Anime".
dir="星野ミライ/雨上がりの空"
titles=("雨上がりの空" "君の街まで" "夏色ノスタルジア" "星降る夜に" "さよならの向こう側")
for i in "${!titles[@]}"; do
  n=$((i + 1)); next
  track "$dir/$(printf '%02d' $n) ${titles[$i]}.m4a" $seed "$WORK/rain.jpg" tone \
    -metadata "title=${titles[$i]}" -metadata "artist=星野ミライ" -metadata "album_artist=星野ミライ" \
    -metadata "album=雨上がりの空" -metadata "track=$n/${#titles[@]}" -metadata "disc=1/1" \
    -metadata "date=2023-04-05" -metadata "genre=J-Pop/Anime" -metadata "composer=星野ミライ"
done
lrc "$dir/01 雨上がりの空.lrc" "雨上がりの空" "星野ミライ" "雨上がりの空に" "虹がかかる" "君と見上げた" "あの日のように"

# 4) Northern Echo / Aurora Lights — flac, two discs (DISCNUMBER 1/2, 2/2), embedded 1200px PNG.
dir="Northern Echo/Aurora Lights"
for disc in 1 2; do
  if [[ $disc == 1 ]]; then titles=("Polar Night" "Borealis" "Frozen Lake"); subtitle="Dusk"
  else titles=("Solar Wind" "Magnetic Dawn" "Aurora (Reprise)"); subtitle="Dawn"; fi
  for i in "${!titles[@]}"; do
    n=$((i + 1)); next
    track "$dir/CD$disc/$(printf '%d-%02d' $disc $n) ${titles[$i]}.flac" $seed "$WORK/aurora.png" tone \
      -metadata "TITLE=${titles[$i]}" -metadata "ARTIST=Northern Echo" -metadata "ALBUMARTIST=Northern Echo" \
      -metadata "ALBUM=Aurora Lights" -metadata "TRACKNUMBER=$n" -metadata "TRACKTOTAL=3" \
      -metadata "DISCNUMBER=$disc/2" -metadata "DISCSUBTITLE=$subtitle" -metadata "DATE=2020-11-02" \
      -metadata "ORIGINALDATE=2018" -metadata "GENRE=Ambient; Electronic"
  done
done

# 5) Various Artists / Summer Hits — compilation (COMPILATION=1), mp3, embedded cover.
dir="Various Artists/Summer Hits 2024"
artists=("林雨晴" "星野ミライ" "Northern Echo" "DJ Mizu" "The Rainy Days")
titles=("海风 (Remix)" "夏祭り" "Heatwave" "Tokyo Drift Summer" "Sunburn")
for i in "${!titles[@]}"; do
  n=$((i + 1)); next
  track "$dir/$(printf '%02d' $n) ${titles[$i]}.mp3" $seed "$WORK/hits.jpg" tone \
    -metadata "title=${titles[$i]}" -metadata "artist=${artists[$i]}" -metadata "album_artist=Various Artists" \
    -metadata "album=Summer Hits 2024" -metadata "track=$n/10" -metadata "compilation=1" \
    -metadata "date=2024" -metadata "genre=Pop"
done

# 6) The Rainy Days / Blue Skies — opus, folder.png (1200px), genre "Pop; Rock", article in name.
dir="The Rainy Days/Blue Skies"
image "$dir/folder.png" 1200 0x38BDF8 0x1D4ED8
titles=("Blue Skies" "Umbrella" "Puddles & Pavements" "Don't Stop the Rain")
for i in "${!titles[@]}"; do
  n=$((i + 1)); next
  track "$dir/$(printf '%02d' $n) ${titles[$i]}.opus" $seed - tone \
    -metadata "TITLE=${titles[$i]}" -metadata "ARTIST=The Rainy Days" -metadata "ALBUMARTIST=The Rainy Days" \
    -metadata "ALBUM=Blue Skies" -metadata "TRACKNUMBER=$n/${#titles[@]}" -metadata "DATE=2018-09-21" \
    -metadata "GENRE=Pop; Rock" -metadata "BPM=$((96 + n * 8))"
done

# 7) Static Noise / Unknown Signals — ogg vorbis, noise, no artwork at all.
dir="Static Noise/Unknown Signals"
titles=("Signal 1" "Signal 2" "Interference" "Dead Air")
for i in "${!titles[@]}"; do
  n=$((i + 1)); next
  track "$dir/$(printf '%02d' $n) ${titles[$i]}.ogg" $seed - noise \
    -metadata "TITLE=${titles[$i]}" -metadata "ARTIST=Static Noise" -metadata "ALBUM=Unknown Signals" \
    -metadata "TRACKNUMBER=$n" -metadata "DATE=2015" -metadata "GENRE=Noise"
done

# 8) Nature Sounds / Field Recordings — wav with RIFF INFO tags.
dir="Nature Sounds/Field Recordings"
titles=("Forest Rain" "Mountain Stream" "Night Crickets")
for i in "${!titles[@]}"; do
  n=$((i + 1)); next
  track "$dir/$(printf '%02d' $n) ${titles[$i]}.wav" $seed - noise \
    -metadata "title=${titles[$i]}" -metadata "artist=Nature Sounds" -metadata "album=Field Recordings" \
    -metadata "track=$n" -metadata "date=2012" -metadata "genre=Field Recording"
done

# 9) A file without any tags (fallbacks: title from file name, [Unknown Artist/Album]).
next
track "Unsorted/untagged demo.mp3" $seed - tone -id3v2_version 0

# 10) Hidden folder: must be ignored by the scanner.
next
track ".hidden/secret.mp3" $seed - tone -metadata "title=SHOULD NOT BE SCANNED (.hidden)"

# ---------------------------------------------------------------- summary

rm -rf "$WORK"
trap - EXIT
visible=$(find . -type f \( -name '*.mp3' -o -name '*.flac' -o -name '*.m4a' -o -name '*.ogg' -o -name '*.opus' -o -name '*.wav' \) \
  -not -path './.*' -not -path '*/@eaDir/*' | wc -l | tr -d ' ')
echo "Rainy test library: $OUT"
echo "  audio files generated: $TRACKS ($visible visible to the scanner, $((TRACKS - visible)) in ignored folders)"
for ext in mp3 flac m4a ogg opus wav lrc jpg png; do
  printf '  %-5s %3s\n' "$ext" "$(find . -type f -name "*.$ext" -not -path './.*' -not -path '*/@eaDir/*' | wc -l | tr -d ' ')"
done
echo "  albums:"
find . -mindepth 2 -maxdepth 3 -type d -not -path './.*' -not -name '@eaDir' -not -name 'CD*' | LC_ALL=C sort | sed 's|^\./|    |'
if command -v du >/dev/null 2>&1; then
  echo "  total size: $(du -sh . | cut -f1)"
fi
