#!/usr/bin/env bash
# Generates a small, fully tagged test library for Rainy into testdata/music (or $1).
#
#   bash scripts/gen-testdata.sh [output-dir]
#
# Requires ffmpeg with libmp3lame, libvorbis, libopus and the native aac/flac encoders.
# Works in Git Bash on Windows and on Linux/macOS. Idempotent: the output directory is
# recreated on every run (it is only deleted if it was created by this script).
#
# Coverage: mp3 (ID3v2.4, UTF-8), flac, m4a (AAC), ogg vorbis, opus, wav; Chinese, Japanese
# and English metadata; a multi-disc album; a compilation; embedded covers (mp3/flac/m4a),
# folder images (cover.jpg, folder.png), an album without art, artist.jpg; synced .lrc
# sidecars and an embedded LYRICS tag; an untagged file; multi-value genres; "3/10" track
# numbers; full dates and bare years; hidden (.hidden) and Synology (@eaDir) folders whose
# audio must be ignored by the scanner.
set -euo pipefail

# Git Bash: never rewrite arguments that look like POSIX paths (we only pass relative paths).
export MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*'
export LC_ALL="${LC_ALL:-C.UTF-8}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/testdata/music}"
MARKER=".rainy-testdata"

die() { echo "gen-testdata: $*" >&2; exit 1; }

command -v ffmpeg >/dev/null 2>&1 || die "ffmpeg is required (https://ffmpeg.org/download.html)"
encoders="$(ffmpeg -hide_banner -encoders 2>/dev/null)"
for enc in libmp3lame libvorbis libopus aac flac pcm_s16le mjpeg png; do
  grep -qE "^ [A-Z.]{6} $enc " <<<"$encoders" || die "ffmpeg lacks the '$enc' encoder"
done

if [[ -e "$OUT" ]]; then
  if [[ -f "$OUT/$MARKER" || -z "$(ls -A "$OUT" 2>/dev/null)" ]]; then
    rm -rf "$OUT"
  else
    die "$OUT exists and was not created by this script; refusing to delete it"
  fi
fi
mkdir -p "$OUT"
cd "$OUT"
echo "generated by scripts/gen-testdata.sh — safe to delete" >"$MARKER"
WORK=".work"
mkdir -p "$WORK"
trap 'rm -rf "$OUT/$WORK"' EXIT

FF=(ffmpeg -hide_banner -loglevel error -nostdin -y)

# ---------------------------------------------------------------- images

# image <out> <size> <color0> <color1>: a diagonal two-colour gradient (solid colour fallback).
image() {
  local out=$1 size=$2 c0=$3 c1=$4
  mkdir -p "$(dirname "$out")"
  if ! "${FF[@]}" -f lavfi -i "gradients=s=${size}x${size}:c0=${c0}:c1=${c1}:x0=0:y0=0:x1=${size}:y1=${size}:d=1" \
      -frames:v 1 -update 1 "$out" 2>/dev/null; then
    "${FF[@]}" -f lavfi -i "color=c=${c0}:s=${size}x${size}:d=1" -frames:v 1 -update 1 "$out"
  fi
}

image "$WORK/summer.jpg" 600 0xF59E0B 0xEF4444     # 测试专辑1 (embedded, mp3)
image "$WORK/rain.jpg" 600 0x6366F1 0x0EA5E9       # テストアルバム1 (embedded, m4a)
image "$WORK/aurora.png" 1200 0x10B981 0x1E3A8A    # Synthetic Album 1 (embedded 1200px PNG, flac)
image "$WORK/hits.jpg" 600 0xEC4899 0x8B5CF6       # Synthetic Album 2 (embedded, mp3)

# ---------------------------------------------------------------- audio

# source <duration> <seed> [noise]: lavfi audio source spec.
source() {
  local d=$1 seed=$2 kind=${3:-tone}
  if [[ $kind == noise ]]; then
    local colors=(pink white brown)
    echo "anoisesrc=d=${d}:c=${colors[$((seed % 3))]}:a=0.15:r=44100"
  else
    echo "sine=frequency=$((220 + (seed * 97) % 660)):sample_rate=44100:duration=${d}"
  fi
}

# duration <seed>: 3–12 seconds.
duration() { echo $((3 + ($1 * 7) % 10)); }

TRACKS=0

# track <out> <seed> <cover|-> <tone|noise> [ffmpeg metadata args...]
track() {
  local out=$1 seed=$2 cover=$3 kind=$4
  shift 4
  local ext="${out##*.}"
  local inputs=(-f lavfi -i "$(source "$(duration "$seed")" "$seed" "$kind")")
  local maps=(-map 0:a)
  local codec=()
  case "$ext" in
    mp3)  codec=(-c:a libmp3lame -b:a 96k -id3v2_version 4 -write_id3v1 0) ;;
    flac) codec=(-c:a flac -sample_fmt s16) ;;
    m4a)  codec=(-c:a aac -b:a 96k) ;;
    ogg)  codec=(-c:a libvorbis -q:a 1) ;;
    opus) codec=(-c:a libopus -b:a 48k) ;;
    wav)  codec=(-c:a pcm_s16le -ar 22050 -ac 1) ;;
    *) die "unsupported extension: $ext" ;;
  esac
  if [[ $cover != - ]]; then
    inputs+=(-i "$cover")
    maps+=(-map 1:v -c:v copy -disposition:v:0 attached_pic)
    if [[ $ext == mp3 || $ext == flac ]]; then
      maps+=(-metadata:s:v "title=Album cover" -metadata:s:v "comment=Cover (front)")
    fi
  fi
  mkdir -p "$(dirname "$out")"
  "${FF[@]}" "${inputs[@]}" "${maps[@]}" "${codec[@]}" -map_metadata -1 \
    -fflags +bitexact -flags:a +bitexact "$@" "$out"
  TRACKS=$((TRACKS + 1))
}

# lrc <file> <title> <artist> <line>...: synced sidecar, one line every 1.5 s.
lrc() {
  local file=$1 title=$2 artist=$3
  shift 3
  {
    printf '[ti:%s]\n[ar:%s]\n[by:rainy gen-testdata]\n' "$title" "$artist"
    local i=0 ms
    for line in "$@"; do
      ms=$((i * 1500))
      printf '[%02d:%02d.%02d]%s\n' $((ms / 60000)) $(((ms / 1000) % 60)) $(((ms % 1000) / 10)) "$line"
      i=$((i + 1))
    done
  } >"$file"
}

seed=0
next() { seed=$((seed + 1)); }

# 1) 示例歌手1 / 测试专辑1 — mp3, ID3v2.4 UTF-8, embedded JPEG cover, "N/6" track numbers, full date.
dir="示例歌手1/测试专辑1 (2021)"
titles=("测试专辑1" "测试歌曲1" "测试歌曲2" "测试歌曲3" "测试歌曲4" "测试歌曲5")
for i in "${!titles[@]}"; do
  n=$((i + 1)); next
  track "$dir/$(printf '%02d' $n) ${titles[$i]}.mp3" $seed "$WORK/summer.jpg" tone \
    -metadata "title=${titles[$i]}" -metadata "artist=示例歌手1" -metadata "album_artist=示例歌手1" \
    -metadata "album=测试专辑1" -metadata "track=$n/${#titles[@]}" -metadata "disc=1/1" \
    -metadata "date=2021-06-18" -metadata "genre=Mandopop" -metadata "composer=示例歌手1" \
    -metadata "comment=测试数据 · generated"
done
# Synology thumbnail folder with audio inside: must be ignored.
next
track "$dir/@eaDir/01 测试专辑1.mp3" $seed - tone -metadata "title=SHOULD NOT BE SCANNED (@eaDir)"

# 2) 示例歌手1 / 测试专辑2 — flac, cover.jpg in the folder, .lrc sidecars, one embedded LYRICS tag,
#    year only, multi-value genre "Pop; Rock".
dir="示例歌手1/测试专辑2 (2019)"
image "$dir/cover.jpg" 600 0x334155 0x0F172A
titles=("测试专辑2" "测试歌曲6" "测试歌曲7" "测试歌曲8" "测试歌曲9")
for i in "${!titles[@]}"; do
  n=$((i + 1)); next
  extra=()
  if [[ $n == 3 ]]; then
    extra=(-metadata $'LYRICS=[00:00.00]测试歌曲7 — 内嵌歌词\n[00:01.50]测试歌词1\n[00:03.00]测试歌词2')
  fi
  track "$dir/$(printf '%02d' $n) ${titles[$i]}.flac" $seed - tone \
    -metadata "TITLE=${titles[$i]}" -metadata "ARTIST=示例歌手1" -metadata "ALBUMARTIST=示例歌手1" \
    -metadata "ALBUM=测试专辑2" -metadata "TRACKNUMBER=$n/${#titles[@]}" -metadata "DATE=2019" \
    -metadata "GENRE=Pop; Rock" "${extra[@]}"
done
lrc "$dir/01 测试专辑2.lrc" "测试专辑2" "示例歌手1" "测试歌词3" "测试歌词4" "测试歌词5" "测试歌词6"
lrc "$dir/02 测试歌曲6.lrc" "测试歌曲6" "示例歌手1" "测试歌词7" "测试歌词8" "测试歌词9"
# artist image next to the artist's album folders.
image "示例歌手1/artist.jpg" 600 0xFDA4AF 0xBE185D

# 3) テスト歌手1 / テストアルバム1 — m4a (AAC), Japanese, embedded cover, genre "J-Pop/Anime".
dir="テスト歌手1/テストアルバム1"
titles=("テストアルバム1" "テスト曲1" "テスト曲2" "テスト曲3" "テスト曲4")
for i in "${!titles[@]}"; do
  n=$((i + 1)); next
  track "$dir/$(printf '%02d' $n) ${titles[$i]}.m4a" $seed "$WORK/rain.jpg" tone \
    -metadata "title=${titles[$i]}" -metadata "artist=テスト歌手1" -metadata "album_artist=テスト歌手1" \
    -metadata "album=テストアルバム1" -metadata "track=$n/${#titles[@]}" -metadata "disc=1/1" \
    -metadata "date=2023-04-05" -metadata "genre=J-Pop/Anime" -metadata "composer=テスト歌手1"
done
lrc "$dir/01 テストアルバム1.lrc" "テストアルバム1" "テスト歌手1" "テスト歌詞1" "テスト歌詞2" "テスト歌詞3" "テスト歌詞4"

# 4) Synthetic Artist 1 / Synthetic Album 1 — flac, two discs (DISCNUMBER 1/2, 2/2), embedded 1200px PNG.
dir="Synthetic Artist 1/Synthetic Album 1"
for disc in 1 2; do
  if [[ $disc == 1 ]]; then titles=("Synthetic Track 1" "Synthetic Track 2" "Synthetic Track 3"); subtitle="Synthetic Disc 1"
  else titles=("Synthetic Track 4" "Synthetic Track 5" "Synthetic Track 6"); subtitle="Synthetic Disc 2"; fi
  for i in "${!titles[@]}"; do
    n=$((i + 1)); next
    track "$dir/CD$disc/$(printf '%d-%02d' $disc $n) ${titles[$i]}.flac" $seed "$WORK/aurora.png" tone \
      -metadata "TITLE=${titles[$i]}" -metadata "ARTIST=Synthetic Artist 1" -metadata "ALBUMARTIST=Synthetic Artist 1" \
      -metadata "ALBUM=Synthetic Album 1" -metadata "TRACKNUMBER=$n" -metadata "TRACKTOTAL=3" \
      -metadata "DISCNUMBER=$disc/2" -metadata "DISCSUBTITLE=$subtitle" -metadata "DATE=2020-11-02" \
      -metadata "ORIGINALDATE=2018" -metadata "GENRE=Ambient; Electronic"
  done
done

# 5) Various Artists / Synthetic Album 2 — compilation (COMPILATION=1), mp3, embedded cover.
dir="Various Artists/Synthetic Album 2 2024"
artists=("示例歌手1" "テスト歌手1" "Synthetic Artist 1" "Synthetic Artist 2" "Synthetic Artist 3")
titles=("测试歌曲10" "テスト曲5" "Synthetic Track 7" "Synthetic Track 8" "Synthetic Track 9")
for i in "${!titles[@]}"; do
  n=$((i + 1)); next
  track "$dir/$(printf '%02d' $n) ${titles[$i]}.mp3" $seed "$WORK/hits.jpg" tone \
    -metadata "title=${titles[$i]}" -metadata "artist=${artists[$i]}" -metadata "album_artist=Various Artists" \
    -metadata "album=Synthetic Album 2 2024" -metadata "track=$n/10" -metadata "compilation=1" \
    -metadata "date=2024" -metadata "genre=Pop"
done

# 6) Synthetic Artist 3 / Synthetic Album 3 — opus, folder.png (1200px), genre "Pop; Rock", article in name.
dir="Synthetic Artist 3/Synthetic Album 3"
image "$dir/folder.png" 1200 0x38BDF8 0x1D4ED8
titles=("Synthetic Album 3" "Synthetic Track 10" "Synthetic Track 11" "Synthetic Track 12")
for i in "${!titles[@]}"; do
  n=$((i + 1)); next
  track "$dir/$(printf '%02d' $n) ${titles[$i]}.opus" $seed - tone \
    -metadata "TITLE=${titles[$i]}" -metadata "ARTIST=Synthetic Artist 3" -metadata "ALBUMARTIST=Synthetic Artist 3" \
    -metadata "ALBUM=Synthetic Album 3" -metadata "TRACKNUMBER=$n/${#titles[@]}" -metadata "DATE=2018-09-21" \
    -metadata "GENRE=Pop; Rock" -metadata "BPM=$((96 + n * 8))"
done

# 7) Synthetic Artist 4 / Synthetic Album 4 — ogg vorbis, noise, no artwork at all.
dir="Synthetic Artist 4/Synthetic Album 4"
titles=("Synthetic Track 13" "Synthetic Track 14" "Synthetic Track 15" "Synthetic Track 16")
for i in "${!titles[@]}"; do
  n=$((i + 1)); next
  track "$dir/$(printf '%02d' $n) ${titles[$i]}.ogg" $seed - noise \
    -metadata "TITLE=${titles[$i]}" -metadata "ARTIST=Synthetic Artist 4" -metadata "ALBUM=Synthetic Album 4" \
    -metadata "TRACKNUMBER=$n" -metadata "DATE=2015" -metadata "GENRE=Noise"
done

# 8) Synthetic Artist 5 / Synthetic Album 5 — wav with RIFF INFO tags.
dir="Synthetic Artist 5/Synthetic Album 5"
titles=("Synthetic Track 17" "Synthetic Track 18" "Synthetic Track 19")
for i in "${!titles[@]}"; do
  n=$((i + 1)); next
  track "$dir/$(printf '%02d' $n) ${titles[$i]}.wav" $seed - noise \
    -metadata "title=${titles[$i]}" -metadata "artist=Synthetic Artist 5" -metadata "album=Synthetic Album 5" \
    -metadata "track=$n" -metadata "date=2012" -metadata "genre=Field Recording"
done

# 9) A file without any tags (fallbacks: title from file name, [Unknown Artist/Album]).
next
track "Unsorted/untagged demo.mp3" $seed - tone -id3v2_version 0

# 10) Hidden folder: must be ignored by the scanner.
next
track ".hidden/secret.mp3" $seed - tone -metadata "title=SHOULD NOT BE SCANNED (.hidden)"

# ---------------------------------------------------------------- summary

rm -rf "$WORK"
trap - EXIT
visible=$(find . -type f \( -name '*.mp3' -o -name '*.flac' -o -name '*.m4a' -o -name '*.ogg' -o -name '*.opus' -o -name '*.wav' \) \
  -not -path './.*' -not -path '*/@eaDir/*' | wc -l | tr -d ' ')
echo "Rainy test library: $OUT"
echo "  audio files generated: $TRACKS ($visible visible to the scanner, $((TRACKS - visible)) in ignored folders)"
for ext in mp3 flac m4a ogg opus wav lrc jpg png; do
  printf '  %-5s %3s\n' "$ext" "$(find . -type f -name "*.$ext" -not -path './.*' -not -path '*/@eaDir/*' | wc -l | tr -d ' ')"
done
echo "  albums:"
find . -mindepth 2 -maxdepth 3 -type d -not -path './.*' -not -name '@eaDir' -not -name 'CD*' | LC_ALL=C sort | sed 's|^\./|    |'
if command -v du >/dev/null 2>&1; then
  echo "  total size: $(du -sh . | cut -f1)"
fi
