import type { VitePWAOptions } from 'vite-plugin-pwa'

/**
 * PWA options (docs/architecture/contract.md §9.4), imported by `vite.config.ts`. Owner: player feature.
 *
 * - `registerType: 'prompt'`: the app shows an "update available" toast
 *   (`features/player/components/pwa-prompt.tsx`, `virtual:pwa-register/react`) instead of
 *   reloading under the listener's feet; the registration is done by that module
 *   (`injectRegister: false`).
 * - Icons in `public/` are generated by `pnpm generate-pwa-assets` (see `pwa-assets.config.ts`).
 */

// Browser chrome / splash colours = the app background (light theme; the dark variant is set
// per colour scheme with <meta name="theme-color" media=…> in index.html).
const THEME_COLOR = '#ffffff'
const BACKGROUND_COLOR = '#ffffff'

export const pwaOptions: Partial<VitePWAOptions> = {
  strategies: 'generateSW',
  registerType: 'prompt',
  injectRegister: false,
  includeAssets: ['favicon.svg', 'favicon.ico', 'apple-touch-icon-180x180.png'],
  manifest: {
    id: '/',
    name: 'Rainy',
    short_name: 'Rainy',
    description: 'Rainy — 自托管音乐库 · Your self-hosted music library',
    lang: 'zh-CN',
    dir: 'ltr',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    display_override: ['standalone', 'minimal-ui'],
    orientation: 'any',
    theme_color: THEME_COLOR,
    background_color: BACKGROUND_COLOR,
    categories: ['music', 'entertainment'],
    prefer_related_applications: false,
    // A music player should not open a second window when launched again.
    launch_handler: { client_mode: ['focus-existing', 'auto'] },
    icons: [
      { src: 'pwa-64x64.png', sizes: '64x64', type: 'image/png' },
      { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
      { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: 'maskable-icon-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
    shortcuts: [
      {
        name: 'Search · 搜索',
        short_name: 'Search',
        url: '/search',
        icons: [{ src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' }],
      },
      {
        name: 'Favorites · 收藏',
        short_name: 'Favorites',
        url: '/favorites',
        icons: [{ src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' }],
      },
    ],
  },
  workbox: {
    globPatterns: ['**/*.{js,css,html,svg,png,ico,woff2,webmanifest}'],
    // The maskable source is only needed by the icon generator.
    globIgnores: ['**/icon-maskable.svg'],
    cleanupOutdatedCaches: true,
    clientsClaim: true,
    navigateFallback: 'index.html',
    navigateFallbackDenylist: [/^\/api(\/|$)/, /^\/rest(\/|$)/],
    // Audio (`/api/stream`), downloads and the SSE feed (`/api/events`) must never be cached —
    // and must not even be proxied: with no matching route the service worker does not call
    // `respondWith`, so the browser fetches them directly (Range requests for <audio> and
    // long-lived event streams are unreliable through a SW, notably on iOS Safari).
    // Do NOT add a catch-all `/api/*` route. (urlPattern functions are serialised into sw.js —
    // keep them self-contained.)
    runtimeCaching: [
      {
        // Cover ids carry a version suffix, so cached images never go stale.
        urlPattern: ({ url, sameOrigin }) => sameOrigin && url.pathname.startsWith('/api/cover/'),
        handler: 'CacheFirst',
        options: {
          cacheName: 'rainy-covers',
          expiration: { maxEntries: 500, maxAgeSeconds: 60 * 60 * 24 * 30, purgeOnQuotaError: true },
          cacheableResponse: { statuses: [200] },
        },
      },
    ],
  },
  devOptions: {
    enabled: false,
  },
}
